### PR TITLE
Document UnitType acceleration()/turnRadius() features

### PR DESCRIPTION
**Pull request by dgant**
@jaj22 did some research into the acceleration() and turnRadius() features of UnitType and figured out what they mean.

### CODE REVIEW

**Comment by heinermann** [comment]
Can you use `develop` as the base branch?

**Comment by dgant** [comment]
@heinermann Done. What's the background behind develop being largely being behind master, btw?

**Comment by heinermann** [comment]
It isn't behind. It's ahead. :/

**Comment by dgant** [comment]
Develop: "This branch is 140 commits ahead, 121 commits behind master." -- hence the confusion 😄

**Pull request merged**
