### PR TITLE
Update quick start instructions to say VS 2017

### LINKED ISSUE #828: Update Quick Start instructions to specify Visual Studio 2017
This came up in https://github.com/bwapi/bwapi/issues/827

* "i. Install **Visual Studio 2013**"

### PR DESCRIPTION
**Pull request by N00byEdge**
Fixes #828

### CODE REVIEW

**Comment by heinermann** [comment]
"into master" 😨

**Comment by N00byEdge** [comment]
Yeah. This is a breaking change. Watch your back.

**Comment by chriscoxe** [comment]
We don't want the develop branch to be be behind master.  Can you merge it into develop?  Also, the https://bwapi.github.io/ page still says "Visual Studio 2013".  Are the steps to update the on-line documentation documented somewhere, and similarly for any other manual steps required as part of an official release, e.g. increasing version numbers in Git and AppVeyor?

**Comment by chriscoxe** [comment]
I have merged it into the develop branch, in #831

**Pull request merged**
