### PR TITLE
Add more options for reading settings for DirectIP SNP

### PR DESCRIPTION
**Pull request by ZetaTwo**
This PR adds additional options for how to provide settings to the DirectIP SNP. This can be used to supply settings in headless setups.

### CODE REVIEW

**Comment by ZetaTwo** [comment]
Will update the PR and remove the socket related changes as soon as possible

**Comment by heinermann** [comment]
Can you target bwapi:develop?

**Comment by ZetaTwo** [comment]
Sure will do.

**Comment by ZetaTwo** [comment]
Ok, I have both cleaned up this PR a bit and opened a new one based on the `develop` branch.

**Comment by N00byEdge** [comment]
Closing as #884 is merged

**Pull request closed without merging**
